version: "3.8"
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: express-tuto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d express-tuto"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.development
    environment:
      NODE_ENV: "development"
    command: ["npx", "prisma", "migrate", "deploy"]
    restart: "no"

  app:
    build: .
    container_name: express-app
    depends_on:
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env.development
    environment:
      NODE_ENV: "development"
    ports:
      - "9999:9999"
    volumes:
      # 画像等の永続化
      - ./storage:/app/storage

volumes:
  postgres_data: