title: AdminAuthoritiesResponse
allOf:
  - type: object
    properties:
      data:
        type: array
        items:
          $ref: ../../../../schemas/models/MyAdminAuthority.yml
required:
  - data